### ISSUE TITLE
Service is not running in background.

### ISSUE THREAD

**Issue by thekundankamal** [theappbusiness/Tracy#1]
When you kill the app in the device is not scanning and not broadcasting any data. Can you please fix the issue

**Comment by KaneCheshire** [comment]
Hello. That's because you've killed the app. Force-terminated apps cannot use Bluetooth, you need to leave the app in the App Switcher on iOS, and on Android leave the service running. That's how the system works.

**Comment by thekundankamal** [comment]
Yes, I have noted thanks for your reply.
