### ISSUE TITLE
null object reference

### ISSUE THREAD

**Issue by Gagandeep1408** [theappbusiness/Tracy#2]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.bluetooth.le.BluetoothLeAdvertiser.startAdvertising(android.bluetooth.le.AdvertiseSettings, android.bluetooth.le.AdvertiseData, android.bluetooth.le.AdvertiseCallback)' on a null object reference

**Comment by KaneCheshire** [comment]
Thanks for the report! Since this is just a demo app it's not a huge deal but feel free to open a PR if you want to fix it :)

**Comment by KaneCheshire** [comment]
Ah I've just thought, you're probably getting this crash because you're running on an emulator, which isn't supported because the eumulator doesn't have a Bluetooth adapter instance (you can't use Bluetooth APIs at all in an emulator). Please try running on a device.
